//
//  PostRouter.swift
//  Clean Swift Project
//
//  Created by Israel3D on 14/05/2019.
//  Copyright (c) 2019 Israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PostRoutingLogic {
    func routeToComments()
}

protocol PostDataPassing {
    var dataStore: PostDataStore? { get }
}

class PostRouter: NSObject, PostRoutingLogic, PostDataPassing {
    
    weak var viewController: PostViewController?
    var dataStore: PostDataStore?
    
    // MARK: Routing
    func routeToComments() {
        let destinationVC = CommentViewController() //define o destino
        var destDataStore = destinationVC.router?.dataStore //define o dataStore (os dados que vao ser passados) do destino
        passDataToComments(source: dataStore!, destination: &destDataStore!) //passa os dados pro destino
        navigateToComments(source: viewController!, destination: destinationVC) // navega até o destino
    }
    
    // MARK: Passing data
    
    func passDataToComments(source: PostDataStore, destination: inout CommentDataStore){
        destination.postId = source.postId
    }

    // MARK: Navigation
    
    func navigateToComments(source: PostViewController, destination: CommentViewController){
        source.show(destination, sender: nil)
    }
}
