//
//  PostInteractor.swift
//  Clean Swift Project
//
//  Created by Israel3D on 14/05/2019.
//  Copyright (c) 2019 Israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostBusinessLogic{
    func loadData(request: Post.Load.Request)
}

protocol PostDataStore{
    //var name: String { get set }
}

class PostInteractor: PostBusinessLogic, PostDataStore{
    
    var presenter: PostPresentationLogic?
    var worker: PostWorker?
    
    func loadData(request: Post.Load.Request)
    {
        worker = PostWorker()
        worker?.fetchData(completionHandler: { (posts) in
            let response = Post.Load.Response(posts: posts)
            self.presenter?.presentPosts(response: response)
        })
        
    }
}
