//
//  PostInteractor.swift
//  Clean Swift Project
//
//  Created by Israel3D on 14/05/2019.
//  Copyright (c) 2019 Israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostBusinessLogic{
    func doLoadData(request: Post.Load.Request)
    func doLoadComments(request: Post.Comments.Request)
}

protocol PostDataStore{
    var postId: Int { get set }
}

class PostInteractor: PostBusinessLogic, PostDataStore{
    
    var presenter: PostPresentationLogic?
    var worker: PostWorker?
    var postId: Int = 0
    
    func doLoadData(request: Post.Load.Request){
        worker = PostWorker()
        worker?.fetchData(completionHandler: { (posts) in
            let response = Post.Load.Response(posts: posts)
            self.presenter?.presentPosts(response: response)
        })
    }
    
    func doLoadComments(request: Post.Comments.Request) {
        let post = request.post
        postId = post.id
        let response = Post.Comments.Response()
        presenter?.presentComments(response: response)
    }
    
}
