//
//  CommentInteractor.swift
//  Clean Swift Project
//
//  Created by Israel3D on 14/05/2019.
//  Copyright (c) 2019 Israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentBusinessLogic
{
  func doLoadComments(request: Comment.Load.Request)
}

protocol CommentDataStore{
  var postId: Int { get set }
}

class CommentInteractor: CommentBusinessLogic, CommentDataStore
{
  var presenter: CommentPresentationLogic?
  var worker: CommentWorker?
  var postId: Int = 0
  
  // MARK: Do LoadComments
  
  func doLoadComments(request: Comment.Load.Request)
  {
    worker = CommentWorker() //instancia o worker
    worker?.fetchData(postId: postId, completionHandler: { (comments) in //chama o método pra carregar os comentários
        let response = Comment.Load.Response(comment: comments)
        self.presenter?.presentSomething(response: response) //envia a resposta pro presenter
    })
    
  }
}
